# Generated by Django 3.1.4 on 2021-01-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210105_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
